### ISSUE TITLE
How to share my game?

### ISSUE THREAD

**Issue by MrJavaWolf** [bornhack/badge2022#1]
I have made a game for the badge which can be found here: https://github.com/MrJavaWolf/BornHack2022Game

![Teaser](https://raw.githubusercontent.com/MrJavaWolf/BornHack2022Game/main/resources/teaser-1.jpg)

Where should I post it?

**Comment by flummer** [comment]
Please do a pull requests updating the [projects section in the README.md file](https://github.com/bornhack/badge2022#projects-running-on-the-badge)
